// <auto-generated />
namespace Linkedin.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FeEditsBayn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeEditsBayn));
        
        string IMigrationMetadata.Id
        {
            get { return "202002142234367_FeEditsBayn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
