// <auto-generated />
namespace Linkedin.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mariam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mariam));
        
        string IMigrationMetadata.Id
        {
            get { return "202002151645298_mariam-"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
