// <auto-generated />
namespace Linkedin.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mariam_RemoverequiredUserFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mariam_RemoverequiredUserFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202002222013042_mariam_Remove-required-UserFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
