// <auto-generated />
namespace Linkedin.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mariamAddrequiredUserfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mariamAddrequiredUserfk));
        
        string IMigrationMetadata.Id
        {
            get { return "202002231452230_mariam-AddrequiredUser-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
